// Code generated by Prismic. DO NOT EDIT.

import ApplicationForm from "./ApplicationForm";
import BottomContactCta from "./BottomContactCta";
import ContactBlocks from "./ContactBlocks";
import DomainesGrid from "./DomainesGrid";
import DomainesList from "./DomainesList";
import FeaturedWine from "./FeaturedWine";
import Geography from "./Geography";
import HeritageNote from "./HeritageNote";
import Hero from "./Hero";
import HowItWorks from "./HowItWorks";
import MembersHero from "./MembersHero";
import MembersTeaser from "./MembersTeaser";
import MembershipTiers from "./MembershipTiers";
import OriginStory from "./OriginStory";
import RichText from "./RichText";
import ThreeColumnFeatures from "./ThreeColumnFeatures";
import WhatsAppPreview from "./WhatsAppPreview";

export const components = {
	application_form: ApplicationForm,
	bottom_contact_cta: BottomContactCta,
	contact_blocks: ContactBlocks,
	domaines_grid: DomainesGrid,
	domaines_list: DomainesList,
	featured_wine: FeaturedWine,
	geography: Geography,
	heritage_note: HeritageNote,
	hero: Hero,
	how_it_works: HowItWorks,
	members_hero: MembersHero,
	members_teaser: MembersTeaser,
	membership_tiers: MembershipTiers,
	origin_story: OriginStory,
	rich_text: RichText,
	three_column_features: ThreeColumnFeatures,
	whats_app_preview: WhatsAppPreview
};